services:
  pixelaw-core:
    image: oostvoort/pixelaw-core:v0.0.19
    container_name: pixelaw-core
    ports:
      - "5050:5050"
      - "3000:3000"
      - "8080:8080"
      - "50051"
    restart: unless-stopped
    networks:
      - pixelaw
    environment:
      - SEED=17885659508068513399
      - TOTAL_ACCOUNTS=4

networks:
  pixelaw:
    driver: bridge

